services:
  web-service:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres_data:
  static_volume: