# Generated by Django 5.0.9 on 2024-10-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='picture',
        ),
    ]
