# Generated by Django 5.1 on 2024-09-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checkbox',
            fields=[
                ('level', models.AutoField(primary_key=True, serialize=False)),
                ('choice', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], default=None, max_length=1, null=True)),
            ],
        ),
    ]
