# Generated by Django 4.2.16 on 2024-10-18 20:40

from django.db import migrations

def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')  # Get the Category model

    # List of category names to create
    categories = [
        "Category 1",
        "Category 2",
        "Category 3",
        "Category 4",
        "Category 5",
    ]

    # Create categories
    for name in categories:
        Category.objects.create(name=name)  # Create a new Category object

class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_id'),  # Change this to the last migration
    ]

    operations = [
        migrations.RunPython(create_initial_categories),  # Run the function to create categories
    ]
