name = "rights_hero_task"
description = ""
version = "1.0.0"
repository = "https://github.com/Abdurahman-hassan/sw_task"
author_name = "Abdelrahman hassan hamdy"
author_github = "https://github.com/Abdurahman-hassan"
author_email = "abdelrahman.hassan.hamdy@gmail.com"
