# Generated by Django 5.1 on 2024-08-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_category_level_alter_category_parent'),
    ]

    operations = [
    ]
